@startuml
'https://plantuml.com/class-diagram



class NameSorterSort{
    + {static} List<String> sortList()
}

class NameSorterBase{
     List<String> Names
   + {static} void main()
    - {static} List<String> convertFile()
}

class NameSorterExport{
    + {static} void exportList()
}

NameSorterBase <|-- NameSorterSort
NameSorterBase <|-- NameSorterExport

@enduml