@startuml
'https://plantuml.com/class-diagram



class Sort{
    + {static} List<String> sortList()
}

class Base{
    +List<String> Names
   + {static} void main()
    - {static} List<String> convertFile()
}

class Export{
    + {static} void exportList()
    FileWriter outputWriter = new FileWriter()
}

Base <|-- Sort
Base <|-- Export

@enduml