@startuml
'https://plantuml.com/class-diagram




class WebsiteGeneratorBase{
        -{static} String SiteName;
        -{static} String AuthorName;
        -{static} String JavaFolder;
        -{static} String CSSFolder;
        +{static} void Output()
        +{static} void UserInput()
}

class WebsiteGenerator{
        + String FileLocation;
        + String Site;
        + String Author;
        + String HTML;
        + String CreateDirectory()
        + boolean CreateHTML()
        + String CreateCSS()
        + String CreateJS()

}
WebsiteGeneratorBase <|-- WebsiteGenerator

@enduml