@startuml
'https://plantuml.com/class-diagram




class WebsiteGeneratorBase{
        -{static} String SiteName
        -{static} String AuthorName
        -{static} String JavaFolder
        -{static} String CSSFolder
        +{static} void Output()
        +{static} void UserInput()
}

class WebsiteGenerator{
        + String FileLocation
        + String Site
        + String Author
          String HTML
        + String CreateDirectory(String Directory)
        + boolean CreateHTML(String Info)
        + String CreateCSS(String Directory)
        + String CreateJS(String Directory)

}
WebsiteGeneratorBase <|-- WebsiteGenerator

@enduml